FROM oven/bun:1

WORKDIR /app

COPY package.json bun.lockb* ./
RUN bun install

# Source files will be mounted as volume for HMR
COPY . .

ENV PORT=3000
EXPOSE 3000

CMD ["bun", "run", "dev", "--host", "0.0.0.0"]
